sudo: false
dist: trusty
cache: bundler

language: ruby

services:
  - redis-server

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
