sudo: false
dist: trusty

language: ruby

services:
  - redis-server

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_3.gemfile
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

script:
  - cat Gemfile.lock
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
