sudo: false
dist: trusty
cache: bundler

language: ruby

services:
  - redis-server

env:
  - DB=postgres
  - DB=mysql

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem update --system
  - gem install bundler
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $TRAVIS_TEST_RESULT
