sudo: false
dist: trusty
cache: bundler

language: ruby

services:
  - redis-server

env:
  - DB=postgres

gemfile:
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

before_script:
  - ls -la
  - env
  - cp $BUNDLE_GEMFILE Gemfile
  - cp $BUNDLE_GEMFILE.lock Gemfile.lock
  - ls -la
  - bundle exec rake test_app

script:
  - bundle exec rake spec

rvm:
  - 2.3
  - 2.4
  - 2.5
