require: rubocop-rspec

inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 6

RSpec/AnyInstance:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
